# ============================================================
# APPLICATION CONFIG
# ============================================================
spring.application.name=payment-system
server.port=8080

# ============================================================
# DATABASE - H2 (dev) / Switch to PostgreSQL in prod
# ============================================================
#spring.datasource.url=jdbc:h2:mem:paymentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:postgresql://localhost:5432/paymentdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=fintech
spring.datasource.password=fintech123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.h2.console.enabled=false

# ============================================================
# REDIS - Idempotency Key Store
# ============================================================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms
# Idempotency key TTL (24 hours)
app.idempotency.ttl-hours=24

# ============================================================
# RABBITMQ - Async Payment Queue
# ============================================================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Queue names
app.queue.payment-processing=payment.processing
app.queue.payment-dlq=payment.dead-letter
app.queue.payment-retry=payment.retry
app.queue.exchange=payment.exchange
app.queue.dlx=payment.dead-letter.exchange

# Retry config
app.payment.max-retry-attempts=3
app.payment.retry-delay-ms=5000

# ============================================================
# JWT
# ============================================================
app.jwt.secret=ThisIsAVerySecretKeyForJWTTokenGenerationInProductionChangeThis256BitKey
app.jwt.expiration-ms=86400000

# ============================================================
# PAYMENT LIMITS
# ============================================================
app.payment.min-amount=0.01
app.payment.max-amount=100000.00
app.payment.daily-limit=500000.00

# ============================================================
# ACTUATOR
# ============================================================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# ============================================================
# LOGGING
# ============================================================
logging.level.com.fintech=DEBUG
logging.level.org.springframework.amqp=INFO
